task: classification

num_classes: 1000

criterion: CrossEntropyLoss

train_dataloader:
  type: DataLoader
  dataset:
    type: ImageNetDataset
    roots:
      - ./dataset/classification/imagenet1k0
      - ./dataset/classification/imagenet1k1
      - ./dataset/classification/imagenet1k2
      - ./dataset/classification/imagenet1k3
    transforms:
      type: Compose
      ops:
        - type: ToImage
        - type: RandomResizedCrop
          size: 224
        - type: RandomHorizontalFlip
          p: 0.5
        - type: ToDtype
          dtype: float32
          scale: true
        - type: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  shuffle: true
  num_workers: 8
  drop_last: true
  pin_memory: true
  total_batch_size: 128

val_dataloader:
  type: DataLoader
  dataset:
    type: ImageNetDataset
    roots:
      - ./dataset/classification/imagenet1kvalid
    transforms:
      type: Compose
      ops:
        - type: ToImage
        - type: Resize
          size: 256
        - type: CenterCrop
          size: 224
        - type: ToDtype
          dtype: float32
          scale: true
        - type: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  shuffle: false
  num_workers: 8
  drop_last: false
  pin_memory: true
  batch_size: 128
