_wandb:
    value:
        cli_version: 0.23.0
        e:
            xkirnnh0k03y4hu5apn1deyuqk9ageqh:
                args:
                    - --train-dirs
                    - dataset/classification/imagenet1k0
                    - dataset/classification/imagenet1k1
                    - dataset/classification/imagenet1k2
                    - dataset/classification/imagenet1k3
                    - --val-dir
                    - dataset/classification/imagenet1kvalid
                    - --variant
                    - luma-fusion
                    - --coeff-window
                    - "4"
                    - --range-mode
                    - studio
                    - --epochs
                    - "100"
                    - --batch-size
                    - "256"
                    - --max-train-images
                    - "50000"
                    - --max-val-images
                    - "5000"
                    - --save-best
                    - --save-last
                    - --wandb
                    - --time-limit-hours
                    - "0.1"
                cpu_count: 20
                cpu_count_logical: 28
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "2001449418752"
                        used: "1736148021248"
                email: firegunneur@outlook.fr
                executable: /home/aduche/Bureau/motion_sight_back_up/R-Yolov1/yolo-v3/Machine-Learning-Collection/ML/Pytorch/object_detection/RT-DETRv2-DCT/pytorchv2-rt-detr/detr-compressed/bin/python
                git:
                    commit: 381e77c4ad1353b449c7965df76352f7ddc8fa9c
                    remote: git@github.com:Fr4cti0n/RT-DETRv2-DCT.git
                gpu: NVIDIA RTX 5000 Ada Generation Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 9728
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX 5000 Ada Generation Laptop GPU
                      uuid: GPU-42c26b1f-c43d-d031-348c-5cdb63e3a0c9
                host: PO-GSSZR34
                memory:
                    total: "67091255296"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.35
                program: -m src.nn.backbone.train_compressed_backbones
                python: CPython 3.13.5
                root: /home/aduche/Bureau/motion_sight_back_up/R-Yolov1/yolo-v3/Machine-Learning-Collection/ML/Pytorch/object_detection/RT-DETRv2-DCT/pytorchv2-rt-detr
                startedAt: "2025-12-17T10:52:36.636547Z"
                writerId: xkirnnh0k03y4hu5apn1deyuqk9ageqh
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
            "2":
                - 1
                - 41
                - 49
                - 63
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.13.5
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
batch_size:
    value: 256
channels_last:
    value: false
coeff_window:
    value: 4
dct_stats_path:
    value: null
epochs:
    value: 100
eta_min:
    value: 0
image_size:
    value: 256
lr:
    value: 0.1
lr_cap:
    value: 0.1
lr_effective:
    value: 0.05
lr_reference_batch:
    value: 512
momentum:
    value: 0.9
range_mode:
    value: studio
seed:
    value: 1337
time_limit_hours:
    value: 0.1
train_dirs:
    value:
        - dataset/classification/imagenet1k0
        - dataset/classification/imagenet1k1
        - dataset/classification/imagenet1k2
        - dataset/classification/imagenet1k3
train_samples:
    value: 50000
trim_coefficients:
    value: true
val_dir:
    value: dataset/classification/imagenet1kvalid
val_samples:
    value: 5000
variant:
    value: luma-fusion
warmup_epochs:
    value: 0
weight_decay:
    value: 0.0001
